services:
  - type: web
    name: slack-proxy
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 app.py
    envVars:
      - key: SLACK_TOKEN
        sync: false